### ISSUE TITLE
How to calculate the x^power mod modulus by using the powm_odd.cu ?

### ISSUE THREAD

**Issue by ivankxt** [NVlabs/CGBN#1]
Hello,

We using powm_odd.cu to calculate the x^power mod modulus (here x > modulus), but we got the errors as:

CGBN error occurred: division overflow
Error reported by instance 40, blockIdx=(5, 0, 0) threadIdx=(0, 0, 0)

In the powm_odd.cu, it requires:  x<modulus, but our sample x > modulus.
Therefore, we want to know how to calculate the x^power mod modulus where x > modulus.

Thank You!
@nemmart

**Comment by nemmart** [comment]
Hi @ivankxt  -- just compute x' = x mod modulus, and then pass x' to powm_odd instead of x.

Assuming that the length of x (in bits) is less than twice the length of the modulus, you can use cgbn_rem_wide for the division. 

Let me know if you have any trouble getting it to work.

**Comment by ivankxt** [comment]
> Hi @ivankxt -- just compute x' = x mod modulus, and then pass x' to powm_odd instead of x.
> 
> Assuming that the length of x (in bits) is less than twice the length of the modulus, you can use cgbn_rem_wide for the division.
> 
> Let me know if you have any trouble getting it to work.

It work!
Thank You!
